import requests

# Prompt user for city name input
city_name = input("Enter a city name (e.g. 'New York, London'): ")

# API key generated by OpenWeather API
API_key = 'your API KEY'

# Make API request to OpenWeatherMap
url = f"http://api.openweathermap.org/data/2.5/weather?q={city_name}&appid={API_key}&units=metric"
response = requests.get(url)

# Check if API request was successful
if response.status_code == 200:
    # Parse JSON response
    data = response.json()
    # Extract relevant weather data
    temperature = data['main']['temp']
    humidity = data['main']['humidity']
    weather_description = data['weather'][0]['description']
    # Display weather data to user
    print(f"City: {city_name}\nTemperature: {temperature}°C\nHumidity: {humidity}%\nWeather: {weather_description}")
else:
    # Display error message to user
    print(f"Error: Could not retrieve weather data for {city_name} due to location not found or API request fails.")
